[package]
name = "cfdyndns"
version = "0.0.2"
authors = ["Cole Mickens <cole.mickens@gmail.com>"]
edition = "2018"

[dependencies]
log = "*"
pretty_env_logger = "*"
reqwest = "*"
serde = "*"
serde_json = "*"
trust-dns = "*"
