[package]
name = "cloudflare-dyndns"
version = "0.1.0"
authors = ["Cole Mickens <cole.mickens@gmail.com>"]

[dependencies]
env_logger = "0.3.1"
serde = "*"
serde_json = "*"
trust-dns = "0.2.0"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
